apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: game

spec:
  selector:
    app: postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: game

spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      nodeSelector:
        game-storage: "true"

      containers:
        - name: postgres
          image: postgres:18

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: game-database
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: game-database
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: game-database
                  key: POSTGRES_DB

          ports:
            - name: postgres
              containerPort: 5432

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - game
                - -d
                - game
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - game
                - -d
                - game
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: postgres-data
          hostPath:
            path: /var/local/game-data/postgres
            type: DirectoryOrCreate
