kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: game-local

nodes:
  # Kubernetes control plane.
  - role: control-plane

    # localhost:8080 on Fedora
    #       ↓
    # NodePort 30080 inside Kubernetes.
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        listenAddress: "127.0.0.1"
        protocol: TCP

  # Worker node where Redis/Postgres persistent storage lives.
  - role: worker

    labels:
      game-storage: "true"

    extraMounts:
      - hostPath: "/home/arthurj/github/smallworld/backend2/.kind-data"
        containerPath: /var/local/game-data
        selinuxRelabel: true

  # Second Kubernetes worker node.
  - role: worker
